config/routes.rb
Qks1::Application.routes.draw do
  namespace :api do
    namespace :v1 do
      get "earthquakes/list"
    end
  end

  match 'earthquakes(.:format)' => 'api/v1/earthquakes#list'
  match 'welcome/home' => 'welcome#home'
  match 'welcome/search' => 'welcome#search'

  root :to => 'welcome#home'

end

app/models/earthquake.rb
class Earthquake < ActiveRecord::Base

  acts_as_mappable :default_units => :miles,
                   :default_formula => :sphere,
                   #:distance_field_name => :distance,
                   :lat_column_name => :lat,
                   :lng_column_name => :lon

  attr_accessible :datetime, :depth, :eqid, :lat, :lon, :magnitude, :nst, :raw, :region, :src, :version

  validates_uniqueness_of :eqid

  # any scope-like class methods go here:
  def self.on(datetime_value)
    datetime = convert_datetime(datetime_value)
    midnight = datetime.to_date
    where(:datetime => (midnight)..(midnight + 1.day))
  end

  def self.since(datetime_value)
    datetime = convert_datetime(datetime_value)
    where(["datetime >= ?", datetime])
  end

  def self.over(magnitude)
    where(["magnitude > ?", magnitude])
  end

  def self.near(lat_and_lon)
    lat,lon,range = lat_and_lon.split(',')
    range ||= 5
    range = range.to_f
    origin = Earthquake.new(:lat => lat, :lon => lon)
    ids = Earthquake.all.select{|q| origin.distance_from(q) < range }.collect{|q| q.id}
    where(["id IN (?)", ids])
  end

  # any scopes should go here:
  # ...

  def self.search(options)
    options ||= {}
    result = Earthquake.where(true)
    result = result.on(options[:on]) unless options[:on].to_s == ''
    result = result.since(options[:since]) unless options[:since].to_s == ''
    result = result.over(options[:over]) unless options[:over].to_s == ''
    result = result.near(options[:near]) unless options[:near].to_s == ''
    #puts result.to_sql
    result
  end

  def self.convert_datetime(datetime_value)
    case datetime_value
    when Fixnum
      Time.at(datetime_value)
    when String
      self.convert_datetime_string(datetime_value)
      when Float
      Time.at(datetime_value)
    else
      datetime_value
    end
  end

  def self.convert_datetime_string(datetime_string)
    if datetime_string =~ /^\d*$/
      Time.at(datetime_string.to_f)
    elsif datetime_string =~ /^(\d*)\/(\d*)\/(\d*)/
      m = $1; d = $2; y = $3
      Time.new(y, m, d)
    elsif datetime_string =~ /^(\d*)-(\d*)-(\d*)/
      y = $1; m = $2; d = $3
      Time.new(y, m, d)
    else
      raise "invalid datetime string"
    end

  end

  def self.oldest
    Earthquake.order('datetime ASC').first
  end

  def self.newest
    Earthquake.order('datetime ASC').last
  end

end

app/controllers/api/earthquakes_controller.rb
class Api::EarthquakesController < ApplicationController
  def list
    puts params
    @earthquakes = Earthquake.all
    respond_to do |format|
      format.html
      format.xml { render :xml => @earthquakes.to_xml }
      format.json { render :json => @earthquakes.to_json }
    end
  end
end

app/controllers/api/v1/earthquakes_controller.rb
class Api::V1::EarthquakesController < ApplicationController
  def list
    @earthquakes = Earthquake.search(params)
    respond_to do |format|
      format.html
      format.xml { render :xml => @earthquakes.to_xml }
      format.json { render :json => @earthquakes.to_json }
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def home
    @earthquake_count = Earthquake.count
    @oldest_earthquake = Earthquake.oldest
    @newest_earthquake = Earthquake.newest
  end

  def search
    @earthquakes = Earthquake.search(params).limit(record_limit)
  end

  private
  def record_limit
    @limit = params[:limit].to_i
    @limit = 20 if @limit <= 0
    params[:limit] = "#{@limit}"
  end
end

app/helpers/api/earthquakes_helper.rb
module Api::EarthquakesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Qks1</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/partials/_earthquake.html.erb
<% if earthquake.nil? %>
    <div><ul><li>missing earthquake data</li></ul></div>
<% else %>
    <div>
      <ul>
        <li><%= earthquake.src %></li>
        <li><%= earthquake.datetime %></li>
        <li><%= earthquake.magnitude %></li>
        <li><%= earthquake.depth %></li>
        <li><%= earthquake.lat %>,<%= earthquake.lon %></li>
        <li><%= earthquake.region %></li>
      </ul>
    </div>
<% end %>

app/views/partials/_earthquake_details.html.erb
<% if earthquake.nil? %>
    <div><ul><li>missing earthquake data</li></ul></div>
<% else %>
    <div>
      <ul>
        <% earthquake.attributes.each do |a, v| %>
          <li><%= a %>: <%= v %></li>
        <% end %>
      </ul>
    </div>
<% end %>

app/views/welcome/home.html.erb
<h1>QuakeWatcher - Keep Track of Recent Earthquakes</h1>
<p>based on <a href="https://explore.data.gov/Geography-and-Environment/Worldwide-M1-Earthquakes-Past-7-Days/7tag-iwnu">https://explore.data.gov/Geography-and-Environment/Worldwide-M1-Earthquakes-Past-7-Days/7tag-iwnu</a></p>

<h2>Search</h2>
<%= link_to "click here to search the database", welcome_search_path %>

<h2>Metadata</h2>
<p>There are <%= @earthquake_count %> earthquakes in the database</p>
<p>The newest earthquake in the database is:
  <%= render :partial => 'partials/earthquake_details', :locals => {:earthquake => @newest_earthquake } %>
</p>
<p>The oldest earthquake in the database is:
  <%= render :partial => 'partials/earthquake_details', :locals => {:earthquake => @oldest_earthquake } %>
</p>

<h2>API (Version 1)</h2>
<p>This app provides an api to search for recent earthquake data</p>
<ul>
  <li>/api/v1/earthquakes</li>
  <li>/api/v1/earthquakes.json</li>
  <li>/api/v1/earthquakes.xml</li>
  <li>/api/v1/earthquakes.json?on=1364582194</li>
  <li>/api/v1/earthquakes.json?since=1364582194</li>
  <li>/api/v1/earthquakes.json?over=6.4</li>
  <li>/api/v1/earthquakes.json?near=36.6702,-114.8870</li>
</ul>

<h2>API Shortcut</h2>
<p>
  You can use /earthquakes as a shortcut to the api urls.
  For example /earthquakes.json is the same as /api/v1/earthquakes.json
</p>

app/views/welcome/search.html.erb
<h1>QuakeWatcher - Search the Earthquakes Database</h1>

<h2>Search</h2>
<p>Enter your search criteria:</p>
<%= form_tag("/welcome/search", method: "get") do %>
    <ul>
      <li>
        <%= label_tag(:on, "Search for earthquakes on a specific date (mm/dd/yyyy):") %>
        <%= text_field_tag(:on, params[:on]) %>
      </li>
      <li>
        <%= label_tag(:since, "Search for earthquakes since a specific date (mm/dd/yyyy):") %>
        <%= text_field_tag(:since, params[:since]) %>
      </li>
      <li>
        <%= label_tag(:over, "Search for earthquakes over a specific magnitude:") %>
        <%= text_field_tag(:over, params[:over]) %>
      </li>
      <li>
        <%= label_tag(:near, "Search for earthquakes near a specific location (lat, lon, range):") %>
        <%= text_field_tag(:near, params[:near]) %>
      </li>
      <li>
        <%= label_tag(:limit, "Limit the number of records returned from the database") %>
        <%= text_field_tag(:limit, params[:limit]) %>
      </li>
    </ul>
    <%= submit_tag("Search") %>
<% end %>

<h2>Search Results</h2>
<% if @earthquakes.nil? %>
    <p>The query returned 0 earthquakes</p>
<% else %>
    <p>The query returned <%= @earthquakes.length %> earthquakes</p>
    <ul>
      <% @earthquakes.each do |earthquake| %>
          <%= render :partial => 'partials/earthquake_details', :locals => {:earthquake => earthquake } %>
      <% end %>
    </ul><% end %>